### ISSUE TITLE
PageSpeed Insights

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#122]
# Tasks

## Pages
- [ ]
- [ ] Home
- [ ] 👨‍💻 About Me
- [ ] 📝 Resume
- [ ] 🖥️ Work Experience
- [ ] 🚀 Personal Projects

## React
- [ ] **⭐💬 Customer Care - Chat Dashboard**
- [ ] **🏦 Commerce Bank - Website**
- [ ] **☔ Insurance company app**

## Front End
- [ ] **🖥️ SaaS Company - Website**

## Other experience
- [ ] **Freelance · Web Developer / Consultant**
- [ ] **Freelance · Web Developer**

## WordPress
- [ ] **📚 SaaS Company - HELP Website**

## QA Automation & Testing
- [ ] **🛒 E-Commerce - Marketplace**

## Other experience
- [ ] **Smartsupp · QA Automation - Team Leader**

## Localization
- [ ] **🖥️ Windows**
