### ISSUE TITLE
Accessibility: Implement ARIA Best Practices

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#128]
**Description:**

- Use ARIA attributes and test with online tools.
- Ensure WCAG compliance as per Next.js documentation.

**Tasks:**

- [ ] Implement ARIA best practices.
- [ ] Test ARIA implementation.
- [ ] Update WCAG-compliant attributes.
