### ISSUE TITLE
Feature(pwa): ✨ Progressive Web App

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#129]
## Description
Convert the web app to follow PWA standards ([web.dev guide](https://web.dev/explore/progressive-web-apps)).

## Benefits
Adopting PWA standards will enhance performance, improve offline support, and increase engagement by making the web app feel more like a native app.

## Implementation
- Add a web app manifest.
- Ensure the app is responsive and meets the required PWA criteria.

## Tasks
- [x] Configure PWA manifest.
- [x] Icons.
- [x] Link in HTML.
- [x] Inspector warnings.
- [x] Try install:
  - [x] Chrome
  - [x] iPhone
  - [x] MacAir locally
- [x] Test PWA functionality.
- [x] Add Lighthouse report - before.
- [x] Add Lighthouse report - after.

## Acceptance Criteria
- The web app works offline.
- The app can be installed on a user's device.
- Performance and loading times are improved.

## Screenshots

Report from **Lighthouse**:

### Before

![Image](https://github.com/user-attachments/assets/5f7595ce-9ffb-43bc-81c5-60b5f25c5cb6)

### After

![Image](https://github.com/user-attachments/assets/92102e56-ef5f-41c4-a283-866b519417c6)

...

**Comment by krsiakdaniel** [comment]
## PR

- ...

## Testing

...

**Comment by krsiakdaniel** [comment]
## Inspector warnings:

![Image](https://github.com/user-attachments/assets/d5586ce6-71f8-49a9-ac0d-4eb1fd99dc32)

**Comment by krsiakdaniel** [comment]
## MASKABLE ICONS

Added ✅ 

It's a good practice to include both a regular icon and a maskable icon to ensure compatibility across all devices and scenarios.

### Regular Icon

- Used by devices that do not support maskable icons.
- Ensures backward compatibility.

### Maskable Icon
- 
- Ensures the icon looks good on devices with non-rectangular shapes.
- Prevents letterboxing.

**Comment by krsiakdaniel** [comment]
## FIXED NEW WARNINGS

All fixed ✅ 

- ⚠️ Richer PWA Install UI won’t be available on desktop. Please add at least one screenshot with the form_factor set to wide.
- ⚠️ Shortcut #1 should include a 96x96 pixel icon.
- ⚠️ Shortcut #2 should include a 96x96 pixel icon.
- ⚠️ Shortcut #3 should include a 96x96 pixel icon.
- ⚠️ Shortcut #4 should include a 96x96 pixel icon.
- ⚠️ Shortcut #5 should include a 96x96 pixel icon.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/254

## Testing

- Tests = Passing ✅
- Web = PWA ✅ 

![Image](https://github.com/user-attachments/assets/a3d795c0-3233-4575-adb3-94adcf1009ce)

![Image](https://github.com/user-attachments/assets/f88bf14b-319a-4869-a0e6-4bdab279d3db)
