### ISSUE TITLE
CI build caching for Next.js project on Netlify

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#140]
**Description:**

- Implement caching for CI.
- https://nextjs.org/docs/pages/building-your-application/deploying/ci-build-caching#netlify-ci

**Tasks:**

- [x] read the docs
- [x] implement caching
- [ ] test on next build if warning persists
- [ ] confirm that the build time is faster

**Screenshots:**

![Image](https://github.com/user-attachments/assets/3b806578-cb22-4277-8cc9-75849690e3bd)

**Comment by krsiakdaniel** [comment]
PR = https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/142

**Comment by krsiakdaniel** [comment]
TESTING

- Works ✅
- Message no longer present.
- Cache is being uploaded correctly.

SCREENSHOTS

![Image](https://github.com/user-attachments/assets/4db2252e-bb91-4f33-a8c3-380bada8c7be)

---

![Image](https://github.com/user-attachments/assets/f38f6c93-bd01-443d-9f4d-384a4221d136)
