### ISSUE TITLE
refactor(comments): 👷 Resolve `TODO`

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#157]
## Description

Make each `TODO` into separate issues.

## Tasks

- [x] TODO 1 = this was done: "// TODO: add E2E tests for inner pages navigation PREV / NEXT for all 'PageNavigation' components"
- [x] TODO 2 = data test ids = PR: https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/248
- [ ] **TODO 3 = meta data into localization = CREATE SOLO ISSUE** 

## Screenshots

![Image](https://github.com/user-attachments/assets/8f0be782-507b-4d9d-9ae9-8a022d16aa33)
