### ISSUE TITLE
refactor(screenshots): 👷 Use latest UI from the website

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#171]
## Description

Need to update personal project `thumb` and `screenshots` on page.

- https://krsiak.cz/personal-projects
- https://krsiak.cz/personal-projects/krsiak

## Benefits

- Better UX and UI.

## Refactoring Plan

- Update images. All **PNG** screenshots, previews and OG images. Redo with latest version. _Save PNGs where needed_ and the rest make **WEBP**.
- Update only the images that actually need it (krsiak.cz, ... other?)

## Tasks

- [x] thumb
- [x] screenshots

## Acceptance Criteria

- [x] Functionality remains unchanged and passes all tests.
- [x] All tests (unit, integration, E2E) pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

![Image](https://github.com/user-attachments/assets/26cbd1c6-065b-442d-a068-becdc592bc8c)

---

![Image](https://github.com/user-attachments/assets/83cc451e-e006-42b6-8eb2-4c2497a485fc)

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/253
