### ISSUE TITLE
docs(issue): 📝 Improve templates

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#181]
## Description

Update templates text, unify a bit, add anything missing.

## Tasks

- [x] [feature-request.md](https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/blob/master/.github/ISSUE_TEMPLATE/feature-request.md)
- [x] [bug-report.md](https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/blob/master/.github/ISSUE_TEMPLATE/bug-report.md)
- [x] [quick-task.md](https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/blob/master/.github/ISSUE_TEMPLATE/quick-task.md)
- [x] [refactoring.md](https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/blob/master/.github/ISSUE_TEMPLATE/refactoring.md)

**Comment by krsiakdaniel** [comment]
## PR

- #182
