### ISSUE TITLE
refactor(contants): 👷  urls and texts from tests and components

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#185]
## Description

Need to move **urls** and **texts** out of the tests and components.

## Benefits

- Enhance code readability.
- Optimize performance.

## Refactoring Plan

- Improve code readability with better naming conventions.
- Modularize or break down complex functions.

## Code Example

Test code.

```ts
await test.step('Check the About Me link', async () => {
  const aboutLink = breadcrumbs.locator(`a[href="/about-me"]`)
  expect(await aboutLink.count()).toBe(1)
  expect(await aboutLink.getAttribute('href')).toBe('/about-me')
})
```

Component code.

```ts
<PageNavigation
  linkPrevious="/"
  namePrevious="Home"
  dataTestIdPrevious={DATA_TEST_IDS.page.aboutMe.previous}
  linkNext="/resume"
  nameNext="Resume"
  dataTestIdNext={DATA_TEST_IDS.page.aboutMe.next}
/>
```

## Tasks

- [ ] refactor: tests
- [ ] refactor: components

## Acceptance Criteria

- [ ] Functionality remains unchanged.
- [ ] All tests pass successfully.
- [ ] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/186

## TESTING

- Tests passing ✅
