### ISSUE TITLE
refactor(contants)!: 👷 folder and files

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#188]
## Description

Split contants into folder and separate files.

## Benefits

- Enhance code readability.

## Refactoring Plan

- Improve code readability with better naming conventions.

## Code Example

Provide a code example if applicable.

```ts
code_example
```

## Tasks

- [x] split main `constants.ts`
- [x] create new files
- [x] check all imports are correct
- [ ] run tests

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/195

## TESTS

Passing ✅
