### ISSUE TITLE
refactor(structure)!: 👷 unify and organize file and folder structure

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#196]
## Description

Restructure the application by organizing components (e.g., `Footer`) into folders and improving naming conventions to create a consistent and logical structure.

## Benefits

- Improved maintainability and scalability.
- Enhanced code readability and consistency across the project.

## Refactoring Plan

- Move related files (e.g., `Footer`) into their respective folders.
- Update naming conventions for folders and files to use either `kebab-case` or `camelCase` consistently, leveraging Copilot recommendations.
- Restructure the application incrementally, focusing on one part at a time to avoid disruptions.

## Code Example

Provide a code example if applicable.

Before:

```ts
/footer/ScrollToTopButton.tsx
footer.tsx

After:

```ts
/footer/
/ScrollToTopButton.tsx
/footer.tsx
```

## Tasks

- [ ] Move components like Footer into their corresponding folders.
- [ ] Update file and folder names for consistency.
- [ ] Verify and update imports across the application.
- [ ] Run all tests to confirm no regressions.

## Acceptance Criteria

- File and folder structures follow a consistent convention.
- All functionality remains intact.
- Tests pass successfully.
- Changes are reviewed and approved via PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/197

## TESTS

Passing ✅
