### ISSUE TITLE
refactor(folders)!: 👷  `kebab-case` naming consistency

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#202]
## Description

Refactor folder names to use kebab case for improved consistency and readability across the project.

## Benefits

- Enhance code readability by standardizing naming conventions.
- Improve maintainability by adhering to a widely-accepted naming style.
- Easier navigation of file system with clear and consistent folder names.

## Refactoring Plan

- Rename folders using kebab case (e.g., `folderName` → `folder-name`).
- Ensure all imports and references to these folders are updated accordingly.
- Run tests to ensure no broken functionality.

## Code Example

```ts
// Before refactor
import { MyComponent } from 'src/components/folderName/Component';

// After refactor
import { MyComponent } from 'src/components/folder-name/Component';
```

## Tasks

- [x] Identify all folders that require renaming.
- [x] Rename folders to kebab case.
- [x] Update all imports and references.
- [x] Run tests to ensure everything works as expected.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/203

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/203
- Merged ✅
