### ISSUE TITLE
test: ✅  test(e2e): ✅ new test for page RESUME

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#210]
## Description

This test aims to verify the breadcrumbs navigation on the Resume page. It will ensure that the Home and Resume links in the breadcrumbs navigate correctly.

## Benefits

Ensuring the breadcrumbs navigation works correctly improves user experience and helps users easily navigate the website.

## Implementation

1. Navigate to the Resume page.
2. Check the Home link in the breadcrumbs.
3. Check the Resume link in the breadcrumbs.

## Code Example

Provide a code example if applicable.

```ts
code_example
```

## Tasks

- [x] Create new test.
- [x] Make sure all works as expcted.

## Acceptance Criteria

- [x] Test is implemented.
- [x] New test passes successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/211
