### ISSUE TITLE
refactor(pages): 👷 highlight text

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#219]
## Description

Refactor the pages to highlight text for better readability and user experience.

## Benefits

- Better UX and UI.

## Refactoring Plan

- Improved readability of the text.
- Implement text highlighting feature.

## Code Example

Provide a code example if applicable.

```ts
code_example
```

## Tasks

- [x] Update texts.
- [x] add `<Highlight text="" />` where needed.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/220
