### ISSUE TITLE
refactor(next-config): 👷 use image patterns

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#221]
## Description

Update the deprecated `images.domains` configuration to the new `images.remotePatterns` configuration.

## Benefits

- Ensure compatibility with the latest configuration standards.

## Refactoring Plan

- Replace `images.domains` with `images.remotePatterns` in the configuration files.
- Use next docs: https://nextjs.org/docs/app/api-reference/components/image#remotepatterns

## Code Example

Provide a code example if applicable.

before 

```ts
const nextConfig = {
  images: {
    domains: ['app.codacy.com', 'github.com', 'img.shields.io', 'api.netlify.com'],
    dangerouslyAllowSVG: true,
    unoptimized: false,
  },
```

after

```ts
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'app.codacy.com',
      },
      {
        protocol: 'https',
        hostname: 'github.com',
      },
      {
        protocol: 'https',
        hostname: 'img.shields.io',
      },
      {
        protocol: 'https',
        hostname: 'api.netlify.com',
      },
    ],
    dangerouslyAllowSVG: true,
    unoptimized: false,
  },
```

## Tasks

- [x] update config

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/222
