### ISSUE TITLE
refactor(imports): 👷 organize in proper order

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#223]
## Description

Refactor all files to ensure that imports are organized at the top of each file. The imports should be split into smaller blocks divided by space for faster reading.

## Benefits

- Enhance code readability.

## Refactoring Plan

Organize imports at the top of each file in the following order:

1. Standard library imports (if applicable)
2. Third-party library imports
3. Absolute imports from your project
4. Relative imports
5. Images, SVG, PNG
6. CSS

## Code Example

before

```ts
import { mindset } from '@/data/expertise/mindset'
import Header from '@/components/header/Header'
import { TEXT } from '@/localization/english'
import { DATA_TEST_IDS } from '@/utils/constants/ids/dataTestIds'
import type { Metadata } from 'next'
import { PAGES_URL } from '@/utils/constants/urls/pageUrls'
```

after

```ts
// Third-Party Library Imports
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactNode } from 'react'
```

```ts
// Custom Hooks
import { useScrollProgress } from '@/hooks/useScrollProgress'
```

```ts
// Components
import PageContainer from '@/components/layout/PageContainer'
import PageNavigation from '@/components/page-navigation/PageNavigation'
import Header from '@/components/header/Header'
import Footer from '@/components/footer/Footer'
```

```ts
// Data
import { mindset } from '@/data/expertise/mindset'
import { iconsSkills1 } from '@/data/skills/skillsMain'
```

```ts
// Utils
import { TEXT } from '@/localization/english'
import { DATA_TEST_IDS } from '@/utils/constants/ids/dataTestIds'
import { PAGES_URL } from '@/utils/constants/urls/pageUrls'
```

```ts
// Interfaces and Helpers
import { getGoBackLinkID } from '@/utils/helpers/getGoBackLink'
import { HeaderSectionProps } from '@/utils/interfaces/componentProps'
import { NavigationDirectionEnum } from '@/utils/interfaces/enums'
```

```ts
// Images
import logo from '@/public/images/webp/logo.webp'
```

```ts
// CSS
import '@/app/custom.css'
```

## Tasks

- [x] organize imports
- [x] split by 1 space relevant blocks
- [x] tests
- [x] app
- [x] components
- [x] data
- [x] hooks
- [x] localization
- [x] utils

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

## Organized

- [x] tests
- [x] app
- [ ] components
- [ ] ...

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/224

## TESTS

- Passing ✅
