### ISSUE TITLE
refactor(metadata): 👷 files per page

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#225]
## Description

Refactor the metadata handling to support a "files per page" structure. This aims to streamline the organization of files for better clarity and maintainability.

## Benefits

- Enhance code readability.
- Improve the developer experience when navigating file structures.

## Refactoring Plan

- Ensure consistent "files per page" structure across the application.

## Code Example

Provide a code example if applicable.

```ts
example
```

## Tasks

- [x] Refactor metadata-related files.

## Acceptance Criteria

- [x] Refactoring maintains existing functionality.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/226
