### ISSUE TITLE
test(refactor): ✅ Remove Shared Variables in Tests

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#227]
## Description

Tests should not have shared variables, texts, URLs, and similar things because if there is a typo or an error, the test won't detect it. Everything in tests should be written manually. The only CONSTANTS allowed are for DATA-TESTID; nothing else. This ensures that the tests will catch any changes in the codebase, as the tests won't rely on shared constants or variables that might have been modified elsewhere.

## Benefits

By hardcoding values directly in your tests, you ensure that any changes in the codebase will be caught by the tests, increasing reliability and accuracy.

## Implementation

Include steps and what is to be tested:

1. Identify sections of the code where shared variables, texts, and URLs are used.
2. Rewrite these sections in tests to hardcode values directly.
3. Ensure that DATA-TESTID constants are still used where appropriate.

## Code Example

Provide a code example if applicable.

```ts
// Example of test without shared variables
test('should display correct title', async ({ page }) => {
  await page.goto('https://example.com');
  const title = await page.locator('[data-testid="page-title"]').textContent();
  expect(title).toBe('Expected Title');
});
```

## Tasks

- [x] Identify shared variables in tests.
- [x] Rewrite tests to hardcode values.
- [x] **EDIT:** Do the same for `TEXT.` localization in tests as well.
- [x] Ensure consistency across all tests.
- [x] Review and refine the tests.

## Acceptance Criteria

- [x] Test is implemented.
- [x] New test passes successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## TODO

- Also refactor: `TEXT.`
- If user makes mistake in localization, that is also in test and shows true but is error in reality

**Comment by krsiakdaniel** [comment]
# PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/228
