### ISSUE TITLE
localization(metadata): 🇬🇧 Move all strings to const

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#249]
## Description

Move all hard-coded strings in the metadata objects to the localization file to ensure consistency and ease of translation.

## Benefits

- Improve maintainability and readability by centralizing strings.
- Facilitate future translations and localization efforts.
- Ensure consistency in text usage across the application.

## Implementation

Include steps and what needs to be moved:
1. Identify and move all hard-coded strings in metadata objects to the `TEXT` object in the localization file (`/localization/english.ts`).
2. Update the metadata objects to use the localized strings.

Folders and files:

```
lib/
└── utils/
    └── metadata/
        ├── pages/
        │   ├── metaDataAboutMe.ts
        │   ├── metaDataProjectsOverviewPersonal.ts
        │   ├── metaDataProjectsOverviewWork.ts
        │   ├── metaDataResume.ts
        │   └── metaDataStatusPage.ts
        ├── projects/
        │   ├── personal/
        │   │   ├── metaDataCryptomania.ts
        │   │   └── metaDataKrsiak.ts
        │   └── work/
        │       ├── metaDataGroupon.ts
        │       ├── metaDataKomercniBanka.ts
        │       ├── metaDataKooperativa.ts
        │       ├── metaDataMoravia.ts
        │       ├── metaDataSmartsuppDashboard.ts
        │       ├── metaDataSmartsuppHelp.ts
        │       └── metaDataSmartsuppWeb.ts
        └── metaDataShared.ts
```

## Code Example

Provide a code example if applicable.

### Before

```ts
import { TEXT } from '@/localization/english';

// TODO: move all strings to localization
export const metaDataSmartsuppWeb = {
  title: `Smartsupp Web | ${TEXT.nameDanielKrsiak} - Front End Developer`,
  description:
    'Worked as a Front End Developer at Smartsupp for 1 year. Created company website Front End, collaborated with UX designer on brand theme and layout.',
  keywords: [
    `${TEXT.nameDanielKrsiak}`,
    'Smartsupp Web',
    'SaaS Company - Website',
    'Front End Developer',
    'Company Website Front End',
    'Documentation Site',
    'Jekyll',
    'Markdown',
    'VuePress',
  ],
};
```

### After

```ts
import { TEXT } from '@/localization/english';

// TODO: move all strings to localization
export const metaDataSmartsuppWeb = {
  title: `${TEXT.smartsuppWebTitle} | ${TEXT.nameDanielKrsiak} - ${TEXT.frontEndDeveloper}`,
  description: TEXT.smartsuppWebDescription,
  keywords: [
    `${TEXT.nameDanielKrsiak}`,
    `${TEXT.smartsuppWeb}`,
    `${TEXT.saasCompanyWebsite}`,
    `${TEXT.frontEndDeveloper}`,
    `${TEXT.companyWebsiteFrontEnd}`,
    `${TEXT.documentationSite}`,
    `${TEXT.jekyll}`,
    `${TEXT.markdown}`,
    `${TEXT.vuePress}`,
  ],
};
```

## Tasks

- [x] Identify and move all hard-coded strings in metadata objects to the TEXT object in the localization file.
- [x] Update the metadata objects to use the localized strings.

## Acceptance Criteria

- [x] All hard-coded strings in metadata objects are moved to the localization file.
- [x] Metadata objects are updated to use the localized strings.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
Possible const structure:

```ts
const META_COMMON = {
  nameDanielKrsiak: 'Daniel Kršiak',
  reactDeveloper: 'React Developer',
  qaAutomation: 'QA Automation',
  teamLeader: 'Team Leader',
  localizationManager: 'Localization Manager',
  javaScript: 'JavaScript',
  react: 'React',
  typeScript: 'TypeScript',
  redux: 'Redux',
  cypress: 'Cypress',
  playwright: 'Playwright',
  dashboardApplication: 'Dashboard application',
  bankingWebsite: 'Banking website',
  saasCompany: 'SaaS company',
  microsoftWindows: 'Microsoft Windows',
  localization: 'Localization',
}

const META = {
  aboutMe: {
    title: `About | ${META_COMMON.nameDanielKrsiak} - ${META_COMMON.reactDeveloper}`,
    description: 'Experienced React Developer proficient in JavaScript, React, TypeScript, Redux. Also skilled in QA Automation, leading teams, and managing localization projects.',
    keywords: [
      META_COMMON.nameDanielKrsiak,
      META_COMMON.reactDeveloper,
      META_COMMON.qaAutomation,
      META_COMMON.teamLeader,
      META_COMMON.localizationManager,
      META_COMMON.javaScript,
      META_COMMON.react,
      META_COMMON.typeScript,
      META_COMMON.redux,
      META_COMMON.cypress,
      META_COMMON.playwright,
      META_COMMON.dashboardApplication,
      META_COMMON.bankingWebsite,
      META_COMMON.saasCompany,
      META_COMMON.microsoftWindows,
      META_COMMON.localization,
    ],
  },
  // Add more metadata entries for other files
}

export const TEXT = {
  ...META_COMMON,
  ...META,
}
```

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/250

## Tests

- Passing ✅
