### ISSUE TITLE
refactor(images): 👷 png to webp

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#251]
## Description

This refactoring aims to convert PNG images to the WebP format.

## Benefits

- Optimize performance.
- Better UX.

## Refactoring Plan

- Update images by converting PNG format to WebP format.
- **Tools:** 
  - https://convertio.co/png-webp/
  - https://cloudconvert.com/png-to-webp
  - https://www.freeconvert.com/png-to-webp/

## Code Example

Provide a code example if applicable.

## Tasks

- [x] Identify all PNG images in the project that make sense to convert.
- [x] Convert each PNG image to WebP format:
  - [x] folder `/personal`
  - [x] folder `/work`
- [x] Convert each PNG image to WebP format.
- [x] Update image references in the codebase to point to the new WebP files.
- [x] Test to ensure that images load correctly and display as intended.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/252
