### ISSUE TITLE
refactor(JSX): 👷 add return type to 'all components'

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#256]
## Description

Refactor all components in the project to include explicit return types (`JSX.Element`) to improve code readability and maintainability for developers.

## Benefits

- Enhance code readability.
- Better DX = Developer Experience.

## Refactoring Plan

- Add explicit return types (`JSX.Element`) to all components.
- Ensure consistent code style and naming conventions.

## Code Example

```ts
type GreetingProps = {
  name: string;
};

const Greeting = ({ name }: GreetingProps): JSX.Element => {
  return <h1>Hello, {name}!</h1>;
};
```

## Tasks

- [x] Identify all components in the project.
- [x] Add explicit return types to each component.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots
Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/257
