### ISSUE TITLE
refactor(components): 👷use react FC<>

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#259]
## Description

Refactor all components in the project to use the `React.FC<>` type to improve code readability and maintainability.

## Benefits

- Enhance code readability.
- Improve type safety.
- Better DX (Developer Experience).

## Refactoring Plan

- Update all components to use the `React.FC<>` type.
- Ensure consistent code style and naming conventions.

## Code Example

Before ...

```ts
type GreetingProps = {
  name: string;
};

const Greeting: = ({ name }: Props) => {
  return <h1>Hello, {name}!</h1>;
};
```

After ...

```ts
type GreetingProps = {
  name: string;
};

const Greeting: FC<GreetingProps> = ({ name }) => {
  return <h1>Hello, {name}!</h1>;
};
```

## Tasks

- [x] Identify all components in the project.
- [x] Update each component to use the `React.FC<>` type.
- [x] Review and test each component for functionality.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/258
