### ISSUE TITLE
performance(smartlook): 🚀 add heatmaps script

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#260]
## Description
The purpose of this feature is to integrate Smartlook heatmaps into the website to track user interactions and gather insights on user behavior.

##  Benefits
- Provides visual insights into user interactions.
- Helps identify areas of improvement on the website.
- Enhances user experience by understanding user behavior.

## Implementation
- Add the Smartlook script to the website.
- Ensure the script is loaded asynchronously.

## Code Example

```js
const Smartlook = () => {
  return (
    <script
      type="text/javascript"
      dangerouslySetInnerHTML={{
        __html: `
          window.smartlook||(function(d) {
          var o=smartlook=function(){ o.api.push(arguments)},h=d.getElementsByTagName('head')[0];
          var c=d.createElement('script');o.api=new Array();c.async=true;c.type='text/javascript';
          c.charset='utf-8';c.src='https://web-sdk.smartlook.com/recorder.js';h.appendChild(c);
          })(document);
          smartlook('init', 'PAGE_KEY', { region: 'eu' });
        `,
      }}
    />
  )
}

export default Smartlook
```

## Tasks

- [x] Add the Smartlook script to the project.
- [x] Verify the script loads correctly on the website.
- [x] Test the integration to ensure data is being collected.

## Acceptance Criteria

- [x] New functionality is implemented.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/261
