### ISSUE TITLE
feature(tracking): ✨ google analytics script

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#266]
## Description

This feature integrates Google Analytics into the website to track user interactions and gather insights on user behavior.

## Benefits

- Provides detailed insights into user interactions.
- Helps identify areas of improvement on the website.

## Implementation

- Add the Google Analytics script to the website.
- Ensure the script is loaded asynchronously.

## Code Example

```
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'GA_KEY');
```

## Tasks

- [x] Add the Google Analytics script to the project.
- [x] Verify the script loads correctly on the website.
- [x] Test the integration to ensure data is being collected.

## Acceptance Criteria

- [x] New functionality is implemented.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

**Comment by krsiakdaniel** [comment]
## PR

- https://github.com/krsiakdaniel/portfolio-website-krsiak-cz/pull/267
